
platform :ios, '11.0'
inhibit_all_warnings!
target 'test' do
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'KJFunctionInject' , :path => "./KJFunctionInject"

end




post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if config.name == 'QA'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', "DEBUG=1", "YX_MODULE_NAME=@(\\\"#{target.name}\\\")"]
        else
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', "YX_MODULE_NAME=@(\\\"#{target.name}\\\")"]
        end
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
  end
end

